window.audioBoards = [
  {
    name: "NightAttack",
    folder: "audio/NightAttack",
    sounds: [
      "hellllllooooo.mp3",
      "correct_a_mundo.mp3",
      "obama_white_folks.mp3",
      "wrong.mp3",
      "special_report.mp3",
      "obama_nothin_on_me.mp3",
      "eff_a_dog.mp3",
      "moth.mp3",
      "omazing_grace.mp3",
      "boo_this_man.mp3",
      "obama_jackass.mp3",
      "shwood_laugh.mp3",
      "credit_mac_daddy.mp3",
      "black_yall.mp3",
      "what.mp3",
      "obama_too_complicated.mp3",
      "brodyquest_2.mp3",
      "racist.mp3",
      "youve_been_rookered.mp3",
      "penny_gtfo.mp3",
      "zelda_game_over.mp3",
      "scared_me_bri.mp3",
      "that_just_happened.mp3",
      "what_is_wrong.mp3",
      "ffvt_winner.mp3",
      "brodyquest_1.mp3",
      "too_gay.mp3",
      "problem_solved.mp3",
      "spaaaaace.mp3",
      "double_complete_rainbow.mp3",
      "jury_diaf.mp3",
      "boulsh.mp3",
      "the_cat_long.mp3",
      "nsfw_intro.mp3",
      "really.mp3",
      "not_real.mp3",
      "ahhh_pimping.mp3",
    ],
  },
];
